version: '3'
services:
  db:
    image: mysql:8.0
    container_name: ${DB_NAME}
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      TZ: Asia/Seoul
